[[headers]]
for = "/*"

  [headers.values]
  Content-Security-Policy = "default-src 'self' api.todoist.com https://cdn.jsdelivr.net/npm/markdown-it@13.0.1/dist/markdown-it.min.js fonts.gstatic.com fonts.googleapis.com https://flowist.netlify.app flowist.app todoist.com;"

[[redirects]]
from = "/secure/"
to = "/.netlify/functions/dynamic"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamic"

[[redirects]]
from = "/"
to = "/secure/"
status = 302
force = true

  [redirects.conditions]
  Cookie = [ "_11ty_oauth_token" ]

[dev]
targetPort = 8_081
