[[headers]]
for = "/*"

  [headers.values]
  Content-Security-Policy = "default-src 'self' api.todoist.com https://cdn.jsdelivr.net/npm/markdown-it@13.0.1/dist/markdown-it.min.js fonts.gstatic.com fonts.googleapis.com;"

[[redirects]]
from = "/secure/"
to = "/.netlify/functions/dynamic"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamic"

[[redirects]]
from = "/app/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[dev]
targetPort = 8081

# use esbuild for bunding
[functions]
  external_node_modules = ["./eleventy-bundler-modules.js", "@11ty/eleventy", "@11ty/dependency-tree", "pug-filters"]
  node_bundler = "esbuild"