[[headers]]
for = "/*"

  [headers.values]
  Content-Security-Policy = "default-src 'self' api.todoist.com;"

[[redirects]]
from = "/secure/"
to = "/.netlify/functions/dynamic"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamic"

[[redirects]]
from = "/app/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[dev]
targetPort = 8_081
